# version: '3.8'
# services:
#   mongodb:
#     image: mongo
#     container_name: my-mongo
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: saumya
#       MONGO_INITDB_ROOT_PASSWORD: password
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
