# services:
#   mongo:
#     image: mongo:7.0
#     platform: linux/amd64
#     restart: always
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: saumya
#       MONGO_INITDB_ROOT_PASSWORD: password
#     volumes:
#       - mongo-data:/data/db

#   backend:
#     build: .
#     platform: linux/amd64
#     restart: always
#     environment:
#       JWT_SECRET: supersecretkey
#       PORT: 5703
#       MONGODB_URL: mongodb://saumya:password@mongo:27017/myMongo?authSource=admin
#       EMAIL_USER: saumyasood6@gmail.com
#       EMAIL_PASS: obtfmjznzxzaucmn
#     depends_on:
#       - mongo

# volumes:
#   mongo-data:
#     driver: local
